---
- name: Create Unbound control keys
  command: unbound-control-setup
  args:
    creates: /var/unbound/etc/unbound_server.pem
  notify:
    - unbound

- name: Configure unbound
  template:
    src: unbound.conf.j2
    dest: /var/unbound/etc/unbound.conf
    owner: root
    group: wheel
    mode: 0644
  notify:
    - unbound

- name: Create NSD control keys
  command: nsd-control-setup
  args:
    creates: /var/nsd/etc/nsd_server.pem
  notify:
    - nsd

- name: Configure NSD
  template:
    src: nsd.conf.j2
    dest: /var/nsd/etc/nsd.conf
    owner: root
    group: _nsd
    mode: 0640
  notify:
    - nsd

- name: Configure root Forward Zone
  template:
    src: root.zone.j2
    dest: /var/nsd/zones/{{ sg_globalconf.domain }}
    owner: root
    group: wheel
    mode: 0644
  notify:
    - nsd

- name: Configure Auxiliary Forward Zones
  template:
    src: forward.zone.j2
    dest: /var/nsd/zones/{{ item.domain }}
    owner: root
    group: wheel
    mode: 0644
  with_items: "{{ sg_network | sg_interfaces_with_attribute('domain') }}"
  loop_control:
    label: "{{ item.domain }}"
  notify:
    - nsd

- name: Configure NSD reverse zone
  template:
    src: reverse.zone.j2
    dest: /var/nsd/zones/{{ item.arpa }}
    owner: root
    group: wheel
    mode: 0644
  with_items: "{{ sg_network | sg_interfaces_with_attribute('hosts') }}"
  loop_control:
    label: "{{ item.cidr }}"
  notify:
    - nsd

- name: Enable DNS services
  copy:
    src: 10-dns
    dest: /etc/rc.conf.local.d/10-dns
    owner: root
    group: wheel
    mode: 0644
  notify:
    - rc.conf.local
